version: '3.5'

services:
  spaceport1:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    container_name: spaceport1
    ports:
      - 81:80
    environment:
      - ASP_INSTANCE_NAME=spaceport1
    
  spaceport2:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    container_name: spaceport2
    ports:
      - 82:80
    environment:
      - ASP_INSTANCE_NAME=spaceport2

  spaceport3:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    container_name: spaceport3
    ports:
      - 83:80
    environment:
      - ASP_INSTANCE_NAME=spaceport3

  spaceport4:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    container_name: spaceport4
    ports:
      - 84:80
    environment:
      - ASP_INSTANCE_NAME=spaceport4
  
  
  web-balancer:
    image: nginx:stable
    container_name: web-balancer
    volumes:
      - .\nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - spaceport1
      - spaceport2
      - spaceport3
      - spaceport4